spring:
  datasource:
    # MySQL
    url: jdbc:mysql://localhost:13306/project_db?serverTimezone=Asia/Seoul
    username: root
    password: password1!
    driver-class-name: com.mysql.cj.jdbc.Driver

    # MariaDB
#    url: jdbc:mariadb://localhost:13307/project_db?serverTimezone=Asia/Seoul
#    username: root
#    password: password1!
#    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # SQL 개행
        highlight_sql: true
        use_sql_comments: true # 실행되는 쿼리문 HINT 표시
        database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true