spring:
  profiles.active: test
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      ddl-auto: validate
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true # templates 디렉토리 검사(파일 없으면 에러 발생)
  output.ansi.enabled: always # 콘솔로그 색상 적용

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
logging:
  charset:
    console: UTF-8
    file: UTF-8
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%clr(%-5level)][%.38t][%logger{39}#%method:%line] - %msg%n"
    file: "[%d{HH:mm:ss.SSS}][%-5level][%.38t][%logger{39}#%method:%line] - %msg%n"