spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true # SQL 개행
        highlight_sql: true
        use_sql_comments: true # 실행되는 쿼리문 HINT 표시
    database-platform: org.hibernate.dialect.H2Dialect
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false # 화면 로딩 시 캐시 비활성화(default: true), 화면 수정이 빈번한 개발환경에서만 캐시 비활성화

logging:
  level:
    root: debug
#  file:
#    name: logs/server.log
